Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hillel_Lesson26_HW.Models;
using Microsoft.AspNetCore.Mvc;
using static System.Net.Mime.MediaTypeNames;


namespace Hillel_Lesson26_HW.Controllers
{
    public class AboutMeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {

            var user = new AboutMeModel()
            {
                FirstName = "Denys",
                LastName = "Klymovets"
            };

            ViewBag.Message = "I am an active, communicable and responsible person. Able to learn fast, find creative solutions and approaches." +
                "Being high-motivated I’m sure I’ll manage to show fast and qualitative growth and we'll build an excellent co-working";

            user.HardSkills = new List<string>()
            {
                "C#/.NET",
                "OOP",
                "HTML5",
                "CSS",
                "JavaScript",
                "GIT",
                "SQL",
                "LINQ",
                "ASP.NET MVC Core",
                "Unit Test",
                "WPF",
                "REST.API",
                "Entity Framework Core"

            };


            return View(user);
        }
    }
}

Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hillel_Lesson26_HW.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Hillel_Lesson26_HW.Controllers
{
    public class ContactsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {

            var contact = new ContactsModel()
            {
                PhoneNumber = "+380996815973",
                Email = "den.kli2511@gmail.com",
                Telegram = "dj_fuego",
                Linkedin = "https://www.linkedin.com/in/denys-klymovets-272a91262/"
            };

            return View(contact);
        }
    }
}

Controllers/EducationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hillel_Lesson26_HW.Models;
using Microsoft.AspNetCore.Mvc;


namespace Hillel_Lesson26_HW.Controllers
{
    public class EducationController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {

            var educationController = new EducationModel();

            var university1 = new EducationModel()
            {
                UniversityName = "Dnipro State Agrarian and Ecomomic University",
                Specialization = "Veterinary Medicine",
                Degree = "Bachelor",
                StydingPeriod = "09.2014 - 12.2018"
            };

            var university2 = new EducationModel()
            {
                UniversityName = "Dnipro State Agrarian and Ecomomic University",
                Specialization = "Public Administration",
                Degree = "Master's",
                StydingPeriod = "09.2018 - 03.2020"
            };

            var university3 = new EducationModel()
            {
                UniversityName = "Learning IT Center “LevelUp",
                StydingPeriod = "07.2022 - 02.2023"
            };

            var university4 = new EducationModel()
            {
                UniversityName = "Hillel IT School",
                StydingPeriod = "03.2023 - 06.2023"
            };

            educationController.EducationModels.Add(university1);
            educationController.EducationModels.Add(university2);
            educationController.EducationModels.Add(university3);
            educationController.EducationModels.Add(university4);


            return View(educationController);
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hillel_Lesson26_HW.Models;
using Microsoft.AspNetCore.Mvc;


namespace Hillel_Lesson26_HW.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {

            var projects = new ProjectsModel();

            projects.ProjectsUrls = new List<string>()
            {
                "https://github.com/R41NB0WD4SH/hillel_lesson25_hw",
                "https://github.com/R41NB0WD4SH/hillel_lesson16_hw",
                "https://github.com/R41NB0WD4SH/hillel_lesson12_hw"
            };

            return View(projects);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hillel_Lesson26_HW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hillel_Lesson26_HW.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hillel_Lesson26_HW</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutMe" asp-action="Index">About Me</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Education" asp-action="Index">Education</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Klymovets Denys CV
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>